spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/Scale_out_session_management
    url: jdbc:mariadb://3.39.226.13:3306/Scale_out_session_management
    username: root
    password: 6548
    hikari:
      minimum-idle: 8
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#  redis:
#    host: localhost
#    port: 6379